#!/usr/bin/env bash

#exit when your script tries to use undeclared variables
set -o nounset

#make your script exit when a command fails
set -o errexit

#The exit status of the last command that threw a non-zero exit code is returned
set -o pipefail

kubectl apply -f docker-private-registry.yml 
kubectl rollout status deploy/docker-private-registry-deployment
kubectl apply -f docker-private-registry-proxy.yml
sleep 5

bash ./port-forward-registry

