#!/usr/bin/env bash

set -o nounset
set -o errexit
set -o pipefail

pid=$(ps -aux| grep 5000:5000 | awk 'NR==1{print $2}')

kubectl delete -f docker-private-registry.yml --ignore-not-found=true 
kubectl delete -f docker-private-registry-proxy.yml --ignore-not-found=true

kill $pid
